### ISSUE TITLE
ImportError: No module named model_conv

### ISSUE THREAD

**Issue by Houchaoqun** [shaohua0116/SSGAN-Tensorflow#1]
when I run this command [python evaler.py --dataset MNIST --checkpoint ckpt_dir], it's wrong and give a message “ImportError: No module named model_conv".
There are two question：
1. Did I miss some .py script about model_conv？
2. Can you help me to change GPU to CPU？
Note：GPU configuration
session_config = tf.ConfigProto(
            allow_soft_placement=True,
            gpu_options=tf.GPUOptions(allow_growth=True),
            device_count={'GPU': 1},
        )

detail：
hcq@hcq-To-be-filled-by-O-E-M:~/deep_learning/SSGAN-Tensorflow$ python evaler.py --dataset MNIST --checkpoint ckpt_dir
[2017-06-11 11:14:43,555] Reading ./datasets/mnist/data.hy ...
[2017-06-11 11:14:43,556] Reading Done: ./datasets/mnist/data.hy
[2017-06-11 11:14:43,556] Reading ./datasets/mnist/data.hy ...
[2017-06-11 11:14:43,556] Reading Done: ./datasets/mnist/data.hy
[2017-06-11 11:14:43,557] self.train_dir = None
[2017-06-11 11:14:43,557] input_ops [inputs]: Using 10000 IDs from dataset
Traceback (most recent call last):
  File "evaler.py", line 205, in <module>
    main()
  File "evaler.py", line 199, in main
    evaler = Evaler(config, dataset_test)
  File "evaler.py", line 81, in __init__
    Model = self.get_model_class(config.model)
  File "evaler.py", line 56, in get_model_class
    from model_conv import Model
ImportError: No module named model_conv

I am very happy to receive your respond, thank you.

**Comment by shaohua0116** [comment]
Fixed it. Please clone it again & thanks for reporting the issue.
The codes should work fine with Tensorflow with CPU support only.

**Comment by Houchaoqun** [comment]
OK, thank you very much. I will try later.
