### ISSUE TITLE
ValueError: num_outputs should be int or long, got 11.

### ISSUE THREAD

**Issue by ZhaohuiXue** [shaohua0116/SSGAN-Tensorflow#14]
Need for help:

Win10
Python 3.6 
tensorflow-gpu            1.4.0                     
tensorflow-tensorboard    0.4.0rc3   

The error is as below by runing 'python trainer.py --dataset MNIST':

-----------------------------------------------------------------------------------------------------------
(C:\Anaconda3) F:\PythonWorkSpace\SSGAN-Tensorflow>python trainer.py --dataset MNIST
[2017-11-28 22:25:31,294] Reading ./datasets/mnist\data.hy ...
[2017-11-28 22:25:31,298] Reading Done: ./datasets/mnist\data.hy
[2017-11-28 22:25:31,300] Reading ./datasets/mnist\data.hy ...
[2017-11-28 22:25:31,312] Reading Done: ./datasets/mnist\data.hy
[2017-11-28 22:25:31,329] Train Dir: ./train_dir/default-MNIST_lr_0.0001_update_G5_D1-20171128-222531
[2017-11-28 22:25:31,330] input_ops [inputs]: Using 60000 IDs from dataset
[2017-11-28 22:25:31,628] input_ops [inputs]: Using 10000 IDs from dataset
[2017-11-28 22:25:31,756] Generator
[2017-11-28 22:25:31,814] Generator Tensor("Generator/g_1_deconv/BatchNorm/Identity:0", shape=(64, 2, 2, 100), dtype=float32)
[2017-11-28 22:25:31,870] Generator Tensor("Generator/g_2_deconv/BatchNorm/Identity:0", shape=(64, 5, 5, 25), dtype=float32)
[2017-11-28 22:25:31,927] Generator Tensor("Generator/g_3_deconv/BatchNorm/Identity:0", shape=(64, 12, 12, 6), dtype=float32)
[2017-11-28 22:25:31,962] Generator Tensor("Generator/g_4_deconv/Tanh:0", shape=(64, 28, 28, 1), dtype=float32)
[2017-11-28 22:25:31,963] Discriminator
[2017-11-28 22:25:32,012] Discriminator Tensor("d_1_conv/dropout/mul:0", shape=(64, 14, 14, 32), dtype=float32)
[2017-11-28 22:25:32,061] Discriminator Tensor("d_2_conv/dropout/mul:0", shape=(64, 7, 7, 64), dtype=float32)
[2017-11-28 22:25:32,167] Discriminator Tensor("d_3_conv/dropout/mul:0", shape=(64, 4, 4, 128), dtype=float32)
Traceback (most recent call last):
  File "trainer.py", line 253, in <module>
    main()
  File "trainer.py", line 247, in main
    dataset_train, dataset_test)
  File "trainer.py", line 50, in __init__
    self.model = Model(config)
  File "F:\PythonWorkSpace\SSGAN-Tensorflow\model.py", line 44, in __init__
    self.build(is_train=is_train)
  File "F:\PythonWorkSpace\SSGAN-Tensorflow\model.py", line 138, in build
    d_real, d_real_logits = D(self.image, scope='Discriminator', reuse=False)
  File "F:\PythonWorkSpace\SSGAN-Tensorflow\model.py", line 123, in D
    tf.reshape(d_3, [self.batch_size, -1]), n+1, scope='d_4_fc', activation_fn=None)
  File "C:\Anaconda3\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "C:\Anaconda3\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1616, in fully_connected
    'num_outputs should be int or long, got %s.' % (num_outputs,))
ValueError: num_outputs should be int or long, got 11.
-----------------------------------------------------------------------------------------------------------
Who can help me? Thank you so much.

**Comment by ZhaohuiXue** [comment]
solved by changing model.py due to the fact that n+1 is numpy int32, whereas slim.fully_connected permits naive python int!!! So, convert n+1 from numpy int32 to python int by **np.asscalar(n+1)**.

d_4 = slim.fully_connected(
                    tf.reshape(d_3, [self.batch_size, -1]), **np.asscalar(n+1)**, scope='d_4_fc', activation_fn=None)

**Comment by BBge** [comment]
Thanks a lot for solving my problem.

**Comment by popcorncolonel** [comment]
Thank you! I had the same problem. Although it's kind of ridiculous that 11 is not automatically converted to an int32.

**Comment by shaohua0116** [comment]
Thanks for the help! I am closing this issue for now.
