### ISSUE TITLE
visualize_training.py is not working

### ISSUE THREAD

**Issue by zlpsls** [shaohua0116/SSGAN-Tensorflow#20]
python visualize_training.py --output_file visualized_sample --train_dir train_dir/default-MNIST_lr_0.0001_update_G5_D1-20180707-195643 --h 28 --w 28 --c 1
train_dir/default-MNIST_lr_0.0001_update_G5_D1-20180707-195643/g_img_0.hy
train_dir/default-MNIST_lr_0.0001_update_G5_D1-20180707-195643/g_img_1000.hy
(2, 224, 224, 1)
Traceback (most recent call last):
  File "visualize_training.py", line 31, in <module>
    imageio.mimsave(args.output_file, II, fps=5)
  File "/usr/local/lib/python2.7/dist-packages/imageio/core/functions.py", line 320, in mimwrite
    writer = get_writer(uri, format, 'I', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/imageio/core/functions.py", line 170, in get_writer
    'in mode %r' % mode)
ValueError: Could not find a format to write the specified file in mode 'I'

**Comment by shaohua0116** [comment]
Please specify the name of your output file by using `--output_file test.png`.
