### ISSUE TITLE
can't create generator

### ISSUE THREAD

**Issue by ahasanpour** [shaohua0116/SSGAN-Tensorflow#8]
I use tensorflow 1.0.0 but after many hours I could not repair this Error, could you please help me?
I examined both python2.7 and 3.5
I also used both types of tensorflow,cpu and gpu!

Connected to pydev debugger (build 171.4249.47)
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
[2017-09-28 16:24:44,037] Reading ./datasets/mnist/data.hy ...
[2017-09-28 16:24:44,038] Reading Done: ./datasets/mnist/data.hy
[2017-09-28 16:24:44,039] Reading ./datasets/mnist/data.hy ...
[2017-09-28 16:24:44,039] Reading Done: ./datasets/mnist/data.hy
[2017-09-28 16:24:44,040] Train Dir: ./train_dir/default-MNIST_lr_0.0001_update_G5_D1-20170928-162444
[2017-09-28 16:24:44,040] input_ops [inputs]: Using 60000 IDs from dataset
Backend TkAgg is interactive backend. Turning interactive mode on.
[2017-09-28 16:26:25,310] input_ops [inputs]: Using 10000 IDs from dataset
Generator
Traceback (most recent call last):
  File "/home/ahp/pycharm-community-2017.1.2/helpers/pydev/pydevd.py", line 1585, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/ahp/pycharm-community-2017.1.2/helpers/pydev/pydevd.py", line 1015, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/ahp/PycharmProjects/tensorflow/SSGAN-Tensorflow-master/trainer.py", line 253, in <module>
    main()
  File "/home/ahp/PycharmProjects/tensorflow/SSGAN-Tensorflow-master/trainer.py", line 247, in main
    dataset_train, dataset_test)
  File "/home/ahp/PycharmProjects/tensorflow/SSGAN-Tensorflow-master/trainer.py", line 50, in __init__
    self.model = Model(config)
  File "/home/ahp/PycharmProjects/tensorflow/SSGAN-Tensorflow-master/model.py", line 46, in __init__
    self.build(is_train=is_train)
  File "/home/ahp/PycharmProjects/tensorflow/SSGAN-Tensorflow-master/model.py", line 137, in build
    fake_image = G(z)
  File "/home/ahp/PycharmProjects/tensorflow/SSGAN-Tensorflow-master/model.py", line 102, in G
    g_1 = deconv2d(z, deconv_info[0], is_train, name='g_1_deconv') 
  File "/home/ahp/.local/lib/python2.7/site-packages/tensorflow/python/layers/convolutional.py", line 1192, in conv2d_transpose
    return layer.apply(inputs)
  File "/home/ahp/.local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 303, in apply
    return self.__call__(inputs, **kwargs)
  File "/home/ahp/.local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 269, in __call__
    self.build(input_shapes[0])
  File "/home/ahp/.local/lib/python2.7/site-packages/tensorflow/python/layers/convolutional.py", line 1043, in build
    dtype=self.dtype)
  File "/home/ahp/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 988, in get_variable
    custom_getter=custom_getter)
  File "/home/ahp/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 890, in get_variable
    custom_getter=custom_getter)
  File "/home/ahp/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 341, in get_variable
    validate_shape=validate_shape)
  File "/home/ahp/.local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 258, in variable_getter
    variable_getter=functools.partial(getter, **kwargs))
  File "/home/ahp/.local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 208, in _add_variable
    trainable=trainable and self.trainable)
  File "/home/ahp/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 333, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/home/ahp/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 628, in _get_single_variable
    shape = tensor_shape.as_shape(shape)
  File "/home/ahp/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 821, in as_shape
    return TensorShape(shape)
  File "/home/ahp/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 457, in __init__
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/home/ahp/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 378, in as_dimension
    return Dimension(value)
  File "/home/ahp/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 33, in __init__
    self._value = int(value)
TypeError: only length-1 arrays can be converted to Python scalars

**Comment by shaohua0116** [comment]
Can you provide the command you use?

**Comment by ahasanpour** [comment]
thanks for your answer,
first I run python download.py --dataset MNIST SVHN and then I tested both below commands

python trainer.py --dataset MNIST
python trainer.py --dataset SVHN

with both of them I got the same error.
actually I use pycharm too, and there is no difference. 
for more details; an array send to value variable in tensorshape.py which it seems it should be a scalar when generative model is constructing.

**Comment by shaohua0116** [comment]
Can you print out the values of `deconv_info` before building the generator?

**Comment by ahasanpour** [comment]
![selection_0401](https://user-images.githubusercontent.com/25530991/31043491-85329ea6-a5c9-11e7-9c7d-c42e7d907696.png)

**Comment by shaohua0116** [comment]
Can you provide the versions of Tensorflow, Numpy, and Python you are using? I am going to reproduce the problem.

**Comment by ahasanpour** [comment]
Sorry for  delay,
I use python 2.7 tensorflow 1.0.0 cpu and numpy 1.12.1

**Comment by ahasanpour** [comment]
could you please say what's your configuration?

**Comment by iNuraj** [comment]
I'm using the same configurations as yours and the model runs perfectly fine. 
Try to delete the downloaded dataset and retry running it like this from the terminal: 
python download.py --dataset MNIST
python trainer.py --dataset MNIST

**Comment by ahasanpour** [comment]
Thank  you iNuraj, 
It's solved, I don't no why actually, I left it alone for some days and I started again everything and just download MNIST and now it is running.
